const mockTicketsList = [
  {
    mockId: "mock-1",
    title: "Dhaka to Chittagong Express",
    from: "Dhaka",
    to: "Chittagong",
    price: 850,
    transportType: "bus",
    quantity: 45,
    perks: ["AC", "WiFi", "Snacks"],
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=400&fit=crop",
    vendorName: "GreenLine Paribahan",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: true,
  },
  {
    mockId: "mock-2",
    title: "Dhaka to Cox's Bazar Direct",
    from: "Dhaka",
    to: "Cox's Bazar",
    price: 1200,
    transportType: "bus",
    quantity: 30,
    perks: ["AC", "Breakfast", "Movie"],
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&h=400&fit=crop",
    vendorName: "Shyamoli Paribahan",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: true,
  },
  {
    mockId: "mock-3",
    title: "Dhaka to Sylhet Intercity Train",
    from: "Dhaka",
    to: "Sylhet",
    price: 450,
    transportType: "train",
    quantity: 120,
    perks: ["AC", "Dining Car"],
    image: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=400&fit=crop",
    vendorName: "Bangladesh Railway",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: true,
  },
  {
    mockId: "mock-4",
    title: "Dhaka to Barishal Launch",
    from: "Dhaka",
    to: "Barishal",
    price: 350,
    transportType: "launch",
    quantity: 200,
    perks: ["Cabin", "Restaurant"],
    image: "https://images.unsplash.com/photo-1527797393658-6a8777f47011?w=800&h=400&fit=crop",
    vendorName: "Sundarban Navigation",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: true,
  },
  {
    mockId: "mock-5",
    title: "Dhaka to Rajshahi Flight",
    from: "Dhaka",
    to: "Rajshahi",
    price: 3500,
    transportType: "plane",
    quantity: 60,
    perks: ["Meal", "Lounge"],
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&h=400&fit=crop",
    vendorName: "US-Bangla Airlines",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: true,
  },
  {
    mockId: "mock-6",
    title: "Dhaka to Khulna Express Train",
    from: "Dhaka",
    to: "Khulna",
    price: 600,
    transportType: "train",
    quantity: 80,
    perks: ["AC", "Breakfast"],
    image: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=400&fit=crop",
    vendorName: "Bangladesh Railway",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: true,
  },
  {
    mockId: "mock-7",
    title: "Comilla to Dhaka Shatabdi",
    from: "Comilla",
    to: "Dhaka",
    price: 280,
    transportType: "train",
    quantity: 150,
    perks: ["AC", "Fast"],
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&h=400&fit=crop",
    vendorName: "Bangladesh Railway",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: false,
  },
  {
    mockId: "mock-8",
    title: "Narayanganj Water Bus",
    from: "Narayanganj",
    to: "Dhaka",
    price: 120,
    transportType: "launch",
    quantity: 300,
    perks: ["Scenic", "Comfortable"],
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&h=400&fit=crop",
    vendorName: "BIWTA Ferries",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: false,
  },
  {
    mockId: "mock-9",
    title: "Mymensingh to Dhaka Express",
    from: "Mymensingh",
    to: "Dhaka",
    price: 200,
    transportType: "bus",
    quantity: 50,
    perks: ["AC", "WiFi"],
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=400&fit=crop",
    vendorName: "Ena Transport",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: false,
  },
  {
    mockId: "mock-10",
    title: "Dhaka to Jessore Flight",
    from: "Dhaka",
    to: "Jessore",
    price: 2800,
    transportType: "plane",
    quantity: 40,
    perks: ["Meal", "Priority Boarding"],
    image: "https://images.unsplash.com/photo-1529074963764-98f45c47344b?w=800&h=400&fit=crop",
    vendorName: "Novoair",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: false,
  },
  {
    mockId: "mock-11",
    title: "Chittagong to Cox's Bazar Coastal Express",
    from: "Chittagong",
    to: "Cox's Bazar",
    price: 400,
    transportType: "bus",
    quantity: 45,
    perks: ["AC", "Snacks"],
    image: "https://images.unsplash.com/photo-1721222339587-41f46a42fb11?q=80&w=800&auto=format&fit=crop",
    vendorName: "SR Travels",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: false,
  },
  {
    mockId: "mock-12",
    title: "Dhaka to Tangail Special Bus",
    from: "Dhaka",
    to: "Tangail",
    price: 180,
    transportType: "bus",
    quantity: 60,
    perks: ["AC"],
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=400&fit=crop",
    vendorName: "Bhuiyan Travels",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: false,
  },
  {
    mockId: "mock-13",
    title: "Dhaka to Rajshahi Silk City Express",
    from: "Dhaka",
    to: "Rajshahi",
    price: 520,
    transportType: "train",
    quantity: 90,
    perks: ["Snack Service", "Air Conditioned"],
    image: "https://images.unsplash.com/photo-1568514328861-5465017e40fc?q=80&w=800&auto=format&fit=crop",
    vendorName: "Bangladesh Railway",
    vendorEmail: "vendor@ticketbari.com",
    isAdvertised: false,
  },
];

const mockMap = new Map();
mockTicketsList.forEach((t) => {
  mockMap.set(t.mockId, t);
  mockMap.set(t.title.toLowerCase(), t);
});

module.exports = {
  mockTicketsList,
  findMockTicket: (idOrTitle) => {
    if (!idOrTitle) return null;
    const str = String(idOrTitle).toLowerCase();
    return mockMap.get(str) || mockMap.get(str.replace("mock-", "")) || null;
  },
};
